### PR TITLE
Fix multiple QueryParams / QueryFlags

### LINKED ISSUE #23: Multiple QueryParams aren't delimited with &
I may have misunderstood, so am quoting the test api / spec I used to narrow down the problem:

### Test API
With this basic API:
```haskell
type QueryStringAPI = "path" :> QueryParam "one" SafeText :> QueryParam "two" SafeText :> Get '[JSON] Text
qsApi:: Proxy QueryStringAPI
qsApi = Proxy

newtype SafeText = SafeText Text
instance ToHttpApiData SafeText
  where toUrlPiece (SafeText st) = st
```

### Spec
..and a `serverSatisifies` spec like:
```haskell
burl = BaseUrl Http "localhost" 8080 ""
spec = it "Query String API doesn't return 500" $
      serverSatisfies qsApi burl stdArgs
        (not500 <%> mempty)

instance Arbitrary SafeText
    -- Ensure it's not the random characters being the problem
    where arbitrary = return $ SafeText "value"
```

### Output
Using a basic HTTP server (`python -m SimpleHTTPServer 8080` here), I see lots of this in the logs:

<tt>127.0.0.1 - - [24/Feb/2017 18:01:06] "GET /path/<strong>?two=valueone=value</strong> HTTP/1.1" 404 -</tt>

Whilst I think the `path/` is covered separately in #22, it's the missing `&` here that means I can't query the real API I was examining. Is this a bug?

Note: a client created with `servant-client` works as expected, with ampersands delimiting multiple (separate) `QueryParam`s...

### PR DESCRIPTION
**Pull request by declension**
* Add test API taking multiple `QueryParam`s
 * Add basic test using this API, generating an endpoint to ensure correct HTTP `one=foo&two=bar` query string generation is happening (that fails on `master`)
 * Fix (re)creation of query string to append `&` before the new parameter if there is already a built query string.

Fixes #23.

### CODE REVIEW

**Comment by declension** [comment]
@jkarni is this along the right lines?

File: src/Servant/QuickCheck/Internal/HasGenRequest.hs [hunk 1]
```diff
@@ -91,9 +91,9 @@ instance (KnownSymbol x, Arbitrary c, ToHttpApiData c, HasGenRequest b)
     genRequest _ = do
       new' <- new
       old' <- old
-      return $ \burl -> let r = old' burl in r {
-          queryString = queryString r
-                     <> param <> "=" <> cs (toQueryParam new') }
+      return $ \burl -> let r = old' burl
+                            qs = queryString r in r {
+          queryString = (if BS.null qs then "" else "&") <> qs <> param <> "=" <> cs (toQueryParam new') }
```
Comment (jkarni) [inline src/Servant/QuickCheck/Internal/HasGenRequest.hs]: Isn't the order of this wrong - i.e., shouldn't it be

```haskell
qs <> (if BS.null qs then "" else "&") <> param <> "=" <> cs (toQueryParam new')
```

File: test/Servant/QuickCheck/InternalSpec.hs [hunk 2]
```diff
@@ -119,6 +135,11 @@ type API = ReqBody '[JSON] String :> Post '[JSON] String
 api :: Proxy API
 api = Proxy
 
+type ParamsAPI = QueryParam "one" String :> QueryParam "two" String :> Get '[JSON] String
```
Comment (jkarni) [inline test/Servant/QuickCheck/InternalSpec.hs]: Instead of `String`, I'd use `()` here. That way, every request is exactly the same, and in the test above you can just check that the query string is *exactly* `one=_&two=_` (IIRC, `_` is what `()` [de]serializes as.

Alternatively, you could use something like `Int`, so that it's easy to check in more details the form of the query string. E.g.  take 4, check that equals `one=`, drop while isNum, take 5, check *that* equals `&two=`.

File: test/Servant/QuickCheck/InternalSpec.hs [hunk 3]
```diff
@@ -107,6 +112,17 @@ isComprehensiveSpec = describe "HasGenRequest" $ do
...
+queryParamsSpec :: Spec
+queryParamsSpec = describe "QueryParams" $ do
+
+  it "reduce to an HTTP query string correctly" $ do
+    let rng = mkQCGen 0
+        burl = BaseUrl Http "localhost" 80 ""
+        gen = genRequest paramsAPI
+        req = (unGen gen rng 0) burl
+        qs = C.unpack $ queryString req
+    qs `shouldContain` ("one=")
```
Comment (jkarni) [inline test/Servant/QuickCheck/InternalSpec.hs]: I think this test doesn't check what I'm concerned about above. Some suggestions below.

File: test/Servant/QuickCheck/InternalSpec.hs (hunk 2 above)
Comment (declension) [inline test/Servant/QuickCheck/InternalSpec.hs]: Great idea! I didn't even think you could use Unit actually, and yes I didn't love those assertions much either. I'll give that a go now

File: src/Servant/QuickCheck/Internal/HasGenRequest.hs (hunk 1 above)
Comment (declension) [inline src/Servant/QuickCheck/Internal/HasGenRequest.hs]: Thanks. FWIW I was trying to preserve the `QueryParam` order, will try another way

File: test/Servant/QuickCheck/InternalSpec.hs [hunk 4]
```diff
@@ -135,7 +134,7 @@ type API = ReqBody '[JSON] String :> Post '[JSON] String
 api :: Proxy API
 api = Proxy
 
-type ParamsAPI = QueryParam "one" String :> QueryParam "two" String :> Get '[JSON] String
+type ParamsAPI = QueryParam "one" String :> QueryParam "two" String :> Get '[JSON] ()
```
Comment (jkarni) [inline test/Servant/QuickCheck/InternalSpec.hs]: Sorry - I meant the type of the query params could be `()` (so that we don't have to rely on the seed being 0). But I'm okay with this!

Comment (declension) [inline test/Servant/QuickCheck/InternalSpec.hs]: Riiiiight. That's better too - I'll update the PR.

In fact I've realised that the bug also applies to `QueryFlag`s so will replicate for those (almost identical)

**Comment by declension** [comment]
@jkarni - thanks. The last update should fix the `QueryFlags` too - hopefully still good to merge.

File: test/Servant/QuickCheck/InternalSpec.hs [hunk 5]
```diff
@@ -107,6 +113,27 @@ isComprehensiveSpec = describe "HasGenRequest" $ do
...
+queryFlagsSpec :: Spec
+queryFlagsSpec = describe "QueryFlags" $ do
+
+  it "reduce to an HTTP query string correctly" $ do
+    let rng = mkQCGen 0
+        burl = BaseUrl Http "localhost" 80 ""
+        gen = genRequest flagsAPI
+        req = (unGen gen rng 0) burl
+        qs = C.unpack $ queryString req
+    qs `shouldBe` "one=&two="
```
Comment (jkarni) [inline test/Servant/QuickCheck/InternalSpec.hs]: Query flags in servant don't have the `=` afterwards!

Comment (declension) [inline test/Servant/QuickCheck/InternalSpec.hs]: Ah yes I see. I'll push a fix

**Comment by jkarni** [comment]
Thanks again! I'll fix the CI issue you mention in #25 and if everything works make a release.
